name: ${pluginName}
main: vg.civcraft.mc.civduties.CivDuties
version: ${version}
depend: [CivModCore]
softdepend: [Vault]
description: ${description}
api-version: ${api_version}
commands:
   duty:
      permission: civduties.duty
permissions:
  civduties.duty:
   default: op
